### ISSUE TITLE
How to get transaction body details

### ISSUE THREAD

**Issue by Wangmmx** [Open-Nyzo/nyzoVerifier#4]
Is there any JSONRPC interface to get the transaction body details by signature hex? Like the explorer does

**Comment by EggPool** [comment]
The Nyzo.today explorer uses a MySql backend and indexes the signatures.

The verifier itself does not.  
You'll need the timestamp or block number in addition, see https://github.com/Open-Nyzo/nyzoVerifier/issues/6

**Comment by Wangmmx** [comment]
Understood, thanks and close the issue
