### ISSUE TITLE
JSONRPC api got an error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Wangmmx** [Open-Nyzo/nyzoVerifier#6]
The method 'transactionconfirmed' of JSONRPC api got an error: java.lang.NullPointerException

Is there something wrong with my code ?

```
curl -X POST http://127.0.0.0:30288/jsonrpc -H 'Content-type:application/json' -d '{"jsonrpc":"2.0","method" :"transactionconfirmed","params" :{"tx":"53deda5c5e53194aae9eb7de7bedc617a7f86d7c91fb49b216b8e0e9d1514526ba71fcfcf6c835b55f3cabc7dc68d82eae0e3ddedfc4dca9b51a33cd7a0a0b00"},"id":1}'
```

**Comment by EggPool** [comment]
Looks like you gave it a signature as `tx` param, and not a raw tx.

The verifier does not index the signatures, and can't retrieve a transaction by its sig alone.   
a transaction buffer contains its timestamp however.  
From that timestamp, the related block is deduced and queried, then parsed to check for the transaction.

So, you need to provide the full tx buffer there, not just its sig.

Another option is to query the target block (known from the timestamp) , then scan its transactions yourself to find your signature.  
7 sec per block, starting at block 0: https://nyzo.co/block/0

**Comment by Wangmmx** [comment]
Yes, I want to query the transaction based on the signature. I see that the parameters in the document are like the signature. Maybe I misunderstood it.
![image](https://user-images.githubusercontent.com/22836587/114524650-faefe880-9c77-11eb-80a2-d0b9201b3799.png)

**Comment by EggPool** [comment]
I confirm tx is supposed to be a tx buffer, not a signature.  
The medium post has a typo, should read "accepts the hex transaction"

**Comment by Wangmmx** [comment]
Ok, I will use the block method to get the txs then, thanks and close this one
