### ISSUE TITLE
Query block error:unknown block

### ISSUE THREAD

**Issue by Wangmmx** [Open-Nyzo/nyzoVerifier#7]
Here is my code 
```
curl -X POST http://127.0.0.0:4000/jsonrpc -H 'Content-type:application/json' -d '{"jsonrpc":"2.0","method" :"block","params" :{"height":11632699},"id":1}'
```

Got the error: `{"id":1,"error":{"code":500,"message":"unknown block"},"jsonrpc":"2.0"}`

I guess it is related to node synchronization? Is my node incomplete or the old block designed by the system cannot be requested?

**Comment by EggPool** [comment]
The node keeps 4 cycles worth of blocks under an accessible form, and can read them back from there.
(if `always_track_blockchain=1` and up for enough time)

It will not give back historical blocks that have been consolidated.  
Older blocks can be read from consolidated files, for instance with pynyzo  
https://github.com/EggPool/pynyzo/blob/ffbb526571017c2f553da298a67bc808a0074e00/pynyzo/pynyzo/block.py#L204

An archive of all consolidated blockfiles can be found there https://nyzo.co/blockFiles

In an exchange or other service context, I'd advise to track the chain and index the data you need as it is frozen.
The 4 cycles long availability is enough for most uses, especially given the fast finality. You know almost right away if a tx is ok or not, and it will not change afterward.

**Comment by Wangmmx** [comment]
Yes, I want to synchronize and save all blocks, I have added the following parameters：
![image](https://user-images.githubusercontent.com/22836587/114526235-5ec6e100-9c79-11eb-9a04-f215f8452602.png)

Did I miss some config?

**Comment by EggPool** [comment]
That's ok.
This will not however guarantee to fetch historical blocks (only since you run it) and the blocks, once consolidated, are no more returned by the rpc calls. 
So, with such a node, uninterrupted and after initial sync, you only access the last 4 cycles worth of blocks.

**Comment by Wangmmx** [comment]
Ok, thank you for all your replies, I will find you again if there is a problem😄
